# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: Docker build
  inputs:
    command: 'build'
    Dockerfile: '**/DockerfileWeb'
    arguments: '-t 542153354/web:v1.0'

- task: CmdLine@2
  displayName: Docker login
  inputs:
    script: 'docker login -u 542153354 -p $(DockerPassword)'

- task: CmdLine@2
  displayName: Docker push
  inputs:
    script: 'docker push 542153354/web:v1.0'

- task: CmdLine@2
  displayName: deploy to Tencent cloud
  inputs:
    script: |
      sshpass -p "$(TencentCloudPassword)" ssh -o StrictHostKeyChecking=no -t -t ubuntu@$(TencentCloudIP) bash -s < deploy-website.sh

- task: CmdLine@2
  displayName: deploy to Ali cloud
  inputs:
    script: |
      sshpass -p "$(AliCloudPassword)" ssh -o StrictHostKeyChecking=no -t -t root@$(AliCloudIP) bash -s < deploy-website.sh